server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.gwolf.vo       # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/mldn_2?serverTimezone=UTC   # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: microcloud-provider-dept
eureka:
  client: #客户端进行Eureka注册的配置
    service-url: 
      defaultZone: http://eureka:eureka@eureka-7001.com:7001/eureka,http://eureka:eureka@eureka-7002.com:7002/eureka,http://eureka:eureka@eureka-7003.com:7003/eureka
  instance:
    instance-id: dept-8002.com  #在信息列表中显示主机名称
    prefer-ip-address: true   #访问的路径变为IP地址
    #lease-renewal-interval-in-seconds: 2  #设置心跳的时间间隔（默认是30秒）
    #lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔（默认90秒）
info:
  app.name: gwolf-microcloud
  company.name: www.gwolf.com
  build.artifactId: $project.artifactId$
  build.version:  $project.version$