server:
  port: 9501
spring:
  application:
    name: microcloud-zuul-gateway
eureka:
  client: #客户端进行Eureka注册的配置
    service-url: 
      defaultZone: http://eureka:eureka@eureka-7001.com:7001/eureka,http://eureka:eureka@eureka-7002.com:7002/eureka,http://eureka:eureka@eureka-7003.com:7003/eureka
  instance:
    instance-id: gateway-9501.com  #在信息列表中显示主机名称
    prefer-ip-address: true   #访问的路径变为IP地址
info:
  app.name: gwolf-microcloud
  company.name: www.gwolf.com
  build.artifactId: $project.artifactId$
  build.version:  $project.version$
  
zuul:
  AuthorizedRequestFilter:
    pre:
      disable:  true
  ignored-services: 
    "*"
  routes: 
    microcloud-provider-dept: /dept-proxy/**
  prefix: /gwolf-proxy
  
security:
  basic:
    enabled: true
  user:
    name: zuul
    password: zuul
  