server:
  port: 7002
eureka:
  instance: #eureka实例定义
    hostname: eureka-7002.com #设置清理的间隔时间，默认这个时间使用的毫秒单单位（默认是60秒）
  client: #客户端进行Eureka注册的配置
      service-url: 
        defaultZone: http://eureka:eureka@eureka-7002.com:7002/eureka,http://eureka:eureka@eureka-7003.com:7003/eureka
      register-with-eureka: false #当前的微服务不注册到eureka之中
      fetch-registry: false
spring:
  application:
    name: microcloud-eureka-7002
security:
  user:
    name: eureka
    password: eureka
